// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztqulzjnyddmpofqmbph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0cXVsempueWRkbXBvZnFtYnBoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxODIyNDQsImV4cCI6MjA2MTc1ODI0NH0.TCR-wPNutPNJ-5kAzNZV3cYXsqeX_XfVvfuSRPvCsYU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);